[package]
name = "servers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
aes_crypt = { git = "https://github.com/Quin-Darcy/aes_crypt.git", branch = "COMMS" }